# Generated by Django 4.2.7 on 2023-11-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_emp', models.CharField(max_length=50)),
                ('email_adm', models.EmailField(max_length=254, unique=True)),
                ('num_func', models.IntegerField()),
                ('area_atua', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
    ]
